import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';

await mkdir('tmp/qa', { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:5173/');
await page.locator('#studio-toggle').click();
await page.waitForFunction(() => window.__fabricStudy?.metrics.maxZ > 0.18);
await page.screenshot({ path: 'tmp/qa/desktop.png', fullPage: true });
console.log('Initial state', await page.evaluate(() => ({ metrics: window.__fabricStudy.metrics, rendering: window.__fabricStudy.rendering })));
await page.getByRole('button', { name: 'Pause simulation', exact: true }).click();
const paused = await page.evaluate(() => window.__fabricStudy.pistons);
await page.waitForTimeout(200);
assert.deepEqual(await page.evaluate(() => window.__fabricStudy.pistons), paused);
await page.getByRole('button', { name: 'Play simulation', exact: true }).click();
await page.locator('#pattern').selectOption('flat');
await page.getByRole('button', { name: 'Front view', exact: true }).click();
await page.locator('#edges').selectOption('fixed');
await page.getByRole('button', { name: 'Select piston row 2 column 3', exact: true }).click();
await page.locator('#piston').fill('220');
await page.locator('#piston').dispatchEvent('input');
await page.waitForFunction(() => window.__fabricStudy.pistons[7] > .2);
assert.equal(await page.evaluate(() => window.__fabricStudy.pistons[0]), 0);
await page.getByRole('button', { name: 'Select piston row 2 column 3', exact: true }).click();
await page.locator('#piston').fill('300');
await page.locator('#piston').dispatchEvent('input');
await page.waitForFunction(() => window.__fabricStudy.pistons[7] > .29);
await page.screenshot({ path: 'tmp/qa/single-peak.png', fullPage: true });
await page.getByRole('button', { name: 'Release override', exact: true }).click();
assert.equal(await page.locator('#piston-value').textContent(), 'Pattern');
await page.locator('#wireframe').check();
await page.screenshot({ path: 'tmp/qa/mesh.png', fullPage: true });
await page.locator('#wireframe').uncheck();
await page.locator('#mechanism').check();
await page.getByRole('button', { name: 'Side view', exact: true }).click();
await page.screenshot({ path: 'tmp/qa/mechanism.png', fullPage: true });
await page.locator('#mechanism').uncheck();
await page.locator('#edges').selectOption('moving');
await page.locator('#pattern').selectOption('wave');
await page.getByRole('button', { name: 'Perspective view', exact: true }).click();
const initialGeometryCount = await page.evaluate(() => window.__fabricStudy.rendering.geometries);
for (const id of ['tension', 'resistance']) {
  assert.equal(await page.locator('#' + id).getAttribute('max'), '300');
  await page.locator('#' + id).fill('300');
  await page.locator('#' + id).dispatchEvent('input');
  assert.equal(await page.locator('#' + id + '-value').textContent(), '3.00×');
}
await page.locator('#columns').selectOption('10');
await page.locator('#rows').selectOption('10');
await page.waitForFunction(() => window.__fabricStudy.rendering.heads === 100 && window.__fabricStudy.pistons[44] > .1);
assert.equal(await page.locator('#piston-grid button').count(), 100);
assert.equal(await page.locator('#point-count').textContent(), '100');
assert.equal(await page.evaluate(() => window.__fabricStudy.settings.resistance), 3);
assert.equal(await page.evaluate(() => window.__fabricStudy.settings.slack), -.2);
await page.getByRole('button', { name: 'Select piston row 10 column 10', exact: true }).click();
await page.locator('#piston').fill('300');
await page.locator('#piston').dispatchEvent('input');
await page.waitForFunction(() => window.__fabricStudy.pistons[99] > .29);
await page.locator('#edges').selectOption('fixed');
assert.ok(await page.locator('#piston').isDisabled());
assert.match(await page.locator('#edge-note').textContent(), /64 interior/);
await page.locator('#edges').selectOption('moving');
await page.locator('#pattern').selectOption('wave');
await page.waitForFunction(() => window.__fabricStudy.pistons[44] > .1);
await page.locator('#columns').scrollIntoViewIfNeeded();
await page.screenshot({ path: 'tmp/qa/grid-10x10.png', fullPage: true });
const clearances = await page.evaluate(() => window.__fabricStudy.rendering);
assert.ok(clearances.minimumHeadClearance > .0099);
assert.ok(clearances.minimumRodClearance > .0219);
// Repeated rebuilds must release geometry and preserve material settings.
for (const [cols, rows] of [['7','8'], ['10','10'], ['5','4']]) {
  await page.locator('#columns').selectOption(cols);
  await page.locator('#rows').selectOption(rows);
  await page.waitForFunction(([c, r]) => window.__fabricStudy.columns === c && window.__fabricStudy.rows === r && window.__fabricStudy.rendering.minimumHeadClearance > .0099, [Number(cols), Number(rows)]);
}
assert.equal(await page.evaluate(() => window.__fabricStudy.rendering.geometries), initialGeometryCount);
assert.equal(await page.locator('#piston-grid button').count(), 20);
assert.equal(await page.evaluate(() => window.__fabricStudy.settings.resistance), 3);
await page.locator('#pattern').selectOption('flat');
await page.waitForFunction(() => window.__fabricStudy.pistons.every(p => p === 0));
await page.screenshot({ path: 'tmp/qa/taut-new.png', fullPage: true });
await page.locator('#columns').selectOption('10');
await page.locator('#rows').selectOption('10');
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'tmp/qa/mobile.png', fullPage: true });
assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
assert.ok(await page.evaluate(() => window.__fabricStudy.finite));
assert.deepEqual(errors, []);
const reduced = await browser.newPage({ reducedMotion: 'reduce' });
await reduced.goto('http://127.0.0.1:5173/');
await reduced.waitForFunction(() => window.__fabricStudy);
assert.equal(await reduced.evaluate(() => window.__fabricStudy.running), false);
console.log('Browser smoke passed: playback, overrides, edge modes, 3× material controls, grid rebuilds to 10×10, rendered clearances, geometry cleanup, mobile layout and reduced motion.');
await browser.close();
