import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1280,height:900}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5173/');
  await page.waitForFunction(()=>window.__fabricStudy?.finite);
  await page.waitForFunction(()=>document.querySelector('#enter-mr').title.length>0);
  assert.equal(await page.locator('#enter-mr').textContent(),'Enter MR');
  assert.ok(await page.locator('#enter-mr').isDisabled());
  await page.screenshot({path:'tmp/qa/xr-desktop.png'});
  const result=await page.evaluate(async()=>{
    const {FabricScene}=await import('/src/scene.ts');
    const {ClothSimulation,RESOLUTIONS}=await import('/src/cloth.ts');
    const {MixedReality}=await import('/src/mixed-reality.ts');
    const host=document.createElement('div');host.style.cssText='width:600px;height:400px';document.body.append(host);
    const view=new FabricScene(host,new ClothSimulation(5,4,RESOLUTIONS[0]));
    const camera=view.camera.position.toArray(),target=view.controls.target.toArray();
    view.cloth.material.wireframe=true;view.cloth.visible=false;
    const restore=view.enterMixedReality();
    const hidden=view.scene.children.filter(c=>c!==view.sculpture).every(c=>!c.visible);
    const entering=hidden&&view.scene.background===null&&!view.controls.enabled&&view.cloth.visible&&!view.cloth.material.wireframe;
    restore();restore();
    const restored=JSON.stringify(view.camera.position.toArray())===JSON.stringify(camera)&&JSON.stringify(view.controls.target.toArray())===JSON.stringify(target)&&!view.cloth.visible&&view.cloth.material.wireframe&&view.scene.background!==null;
    const xr=new EventTarget();let requested,ended=0,session;
    xr.isSessionSupported=async()=>true;
    xr.requestSession=async(mode,options)=>{
      requested={mode,options};session=new EventTarget();session.environmentBlendMode='alpha-blend';
      session.end=async()=>{ended++;session.dispatchEvent(new Event('end'));};return session;
    };
    Object.defineProperty(navigator,'xr',{configurable:true,value:xr});
    const space=new EventTarget();
    view.renderer.xr.setSession=async()=>{};view.renderer.xr.getReferenceSpace=()=>space;
    const mr=new MixedReality(view);await Promise.resolve();
    const button=document.getElementById('play').nextElementSibling;button.click();
    await new Promise(r=>setTimeout(r,0));
    const frame={getViewerPose:()=>({transform:{position:{x:0,y:1.7,z:0},orientation:{x:0,y:0,z:0,w:1}}})};
    mr.update(frame);
    const placed=view.sculpture.position.toArray(),visible=view.sculpture.visible;
    mr.update({getViewerPose:()=>({transform:{position:{x:5,y:1.7,z:2},orientation:{x:0,y:0,z:0,w:1}}})});
    const stationary=JSON.stringify(placed)===JSON.stringify(view.sculpture.position.toArray());
    const select=new Event('select');select.inputSource={targetRaySpace:{}};
    select.frame={...frame,getPose:()=>({transform:{position:{x:0,y:1.6,z:0},orientation:{x:-Math.sin(Math.PI/8),y:0,z:0,w:Math.cos(Math.PI/8)}}})};
    session.dispatchEvent(select);const selected=view.sculpture.position.toArray();
    await session.end();await Promise.resolve();
    const endedCleanly=!view.mixedReality&&view.sculpture.position.length()===0&&!document.body.classList.contains('in-xr');
    xr.requestSession=async()=>{throw new DOMException('User denied','NotAllowedError');};button.click();await new Promise(r=>setTimeout(r,0));
    const denied=!view.mixedReality&&!button.disabled&&button.title.includes('User denied');
    view.renderer.dispose();host.remove();
    return {entering,restored,mode:requested.mode,floor:requested.options.requiredFeatures,placed,visible,stationary,selected,ended,endedCleanly,denied};
  });
  assert.ok(result.entering&&result.restored&&result.visible&&result.stationary&&result.endedCleanly&&result.denied);
  assert.equal(result.mode,'immersive-ar');assert.deepEqual(result.floor,['local-floor']);
  assert.deepEqual(result.placed,[1.8,.9275,-1.5]);
  assert.ok(Math.abs(result.selected[2]+1.6)<1e-6);assert.equal(result.ended,1);
  assert.deepEqual(errors,[]);
  console.log('Desktop fallback, scene restore, mocked AR lifecycle and placement passed.',result);
} finally {await browser.close();}

